「✨」 feat(Flake): added nix flake for easier install
Namonay/fastclass pull request #5
Opened 2024-11-20 20:35 UTC by KeyZox71

Added a little flake that compile the binary and put it into a nixpkgs ❄️

2024-11-20 20:38 UTC, KeyZox71 commented
Should do a home-manager module for the USER and EMAIL environment variable tho

2024-11-24 20:38 UTC, xtrm-en requested changes

2024-11-24 20:38 UTC, xtrm-en commented on flake.nix
> +				buildPhase = ''
Pas nécessaire, `make` est test par default

2024-11-24 20:38 UTC, xtrm-en commented on flake.nix
> +		supportedSystems = [ "x86_64-linux" ];
Utilise https://github.com/nix-systems/ pour le support

2025-08-09 13:52 UTC, closed without merging